# Generated by Django 3.2.7 on 2021-09-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('course_number', models.IntegerField()),
                ('instructor_name', models.CharField(blank=True, default='', max_length=60)),
                ('duration', models.DecimalField(decimal_places=1, default=0.0, max_digits=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Algebra',
            fields=[
                ('djangoclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classApp.djangoclasses')),
            ],
            bases=('classApp.djangoclasses',),
        ),
        migrations.CreateModel(
            name='Biology',
            fields=[
                ('djangoclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classApp.djangoclasses')),
            ],
            bases=('classApp.djangoclasses',),
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('djangoclasses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classApp.djangoclasses')),
            ],
            bases=('classApp.djangoclasses',),
        ),
    ]
