# Generated by Django 3.2.7 on 2021-09-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biology',
            name='djangoclasses_ptr',
        ),
        migrations.RemoveField(
            model_name='english',
            name='djangoclasses_ptr',
        ),
        migrations.DeleteModel(
            name='Algebra',
        ),
        migrations.DeleteModel(
            name='Biology',
        ),
        migrations.DeleteModel(
            name='English',
        ),
    ]
